### ISSUE TITLE
Config-related Crash?

### ISSUE THREAD

**Issue by Enderborn1235** [ArkadiyHimself/Fantazia#1]
[crash-2024-11-18_12.19.15-client.txt](https://github.com/user-attachments/files/17804686/crash-2024-11-18_12.19.15-client.txt)

**Comment by ArkadiyHimself** [comment]
Greetings!
I am not completely sure what in that crash log gives an idea that the crash is related directly to my mod;
Could you please describe when and in what circumstances this crash happens? And how it is related to config specifically
This way I will have a better idea on how to deal with this problem

**Comment by Enderborn1235** [comment]
It only seems to happen when your mod is installed. I'm honestly not sure if its related to a config. I've tried deleting my config folder entirely, but it still happens.

**Comment by Enderborn1235** [comment]
I think I figured it out. I am missing playeranimator, which is used for your mod.

**Comment by ArkadiyHimself** [comment]
You also need curios and patchouli

**Comment by Enderborn1235** [comment]
I did have those already, yes.
